site_name: Metro Extracts
docs_dir: src/metro-extracts
site_dir: dist/metro-extracts
include_next_prev: false # next/prev is in alpha order; we don't want this

extra:
  site_subtitle: Download city-sized portions of OpenStreetMap data in a variety of formats.
  project_repo_url: https://github.com/mapzen/metroextractor-cities
  docs_base_url: https://github.com/mapzen/mapzen-docs/tree/master/metro-extracts
  exclude_home_contents_in_toc: false
