site_name: Developer overview
docs_dir: src-overview
site_dir: dist-overview

pages:
  - Overview: index.md
  - "Doesn't exist": break-me.md
  - "testing": not-here.md

extra:
  site_subtitle: Get started developing with Mapzen's products
  project_repo_url: https://github.com/mapzen/mapzen-docs-generator
  docs_base_url: https://github.com/mapzen/mapzen-docs-generator/tree/master/docs/overview
  exclude_home_contents_in_toc: false
