#   !! DO NOT DELETE THIS FILE !!
#
# This is a test config for the src/test files that are intended ONLY
# for local testing of styles, pipelines etc. This allows us to check in
# to the repository things we want to test against as we develop the pipeline,
# without disturbing actual documentation sources.
# Test files will NOT be deployed to remote development or production servers.
# They are only intended for LOCAL development environments.

site_name: Test
repo_url: https://github.com/valhalla/valhalla-docs
remote_branch: master
google_analytics: ['UA-47035811-1', 'mapzen.com']
docs_dir: src/test
theme: mkdocs
theme_dir: theme
site_dir: dist/test
include_nav: true
include_next_prev: true
extra_css: [css/codehilite/mapzen.css]

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set
# to true to halt processing when a broken link is found, false prints a warning.
strict: true

markdown_extensions:
  - smarty
  - toc:
      permalink: ' ' # Blank space; this marker is styled in CSS.
  - sane_lists
  - nl2br
  - outline
  - codehilite
  # Set of PyMdown extensions to flesh out GFM-mimicry
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.githubemoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra:
  site_subtitle: 'This is a sample for the documentation pipeline.'
  project_repo_url: https://github.com/mapzen/mapzen-docs-generator
  docs_base_url: https://github.com/mapzen/mapzen-docs-generator/blob/master/src/test
  display_project_name_api_key: true
  exclude_home_contents_in_toc: true
