#   !! DO NOT DELETE THIS FILE !!
#
# This is a test config for the src/test files that are intended ONLY
# for local testing of styles, pipelines etc. This allows us to check in
# to the repository things we want to test against as we develop the pipeline,
# without disturbing actual documentation sources.
# Test files will NOT be deployed to remote development or production servers.
# They are only intended for LOCAL development environments.

site_name: Test
repo_url: https://github.com/valhalla/valhalla-docs
docs_dir: src/test
site_dir: dist/test

extra:
  site_subtitle: 'This is a sample for the documentation pipeline.'
  project_repo_url: https://github.com/mapzen/mapzen-docs-generator
  docs_base_url: https://github.com/mapzen/mapzen-docs-generator/blob/master/src/test
