site_name: Valhalla
repo_url: https://github.com/valhalla/valhalla-docs
remote_branch: master
google_analytics: ['UA-47035811-1', 'mapzen.com']
docs_dir: src/valhalla
theme: mkdocs
theme_dir: theme
site_dir: dist/valhalla
include_nav: true
include_next_prev: true
extra_css: [css/codehilite/mapzen.css]

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set
# to true to halt processing when a broken link is found, false prints a warning.
strict: true
pages:
  - Home: index.md
  - 'API Reference': 'api-reference.md'
  - 'Terminology': 'terminology.md'
  - 'LRM-Valhalla walkthrough': 'lrm-valhalla-walkthrough.md'

markdown_extensions:
  - smarty
  - toc:
      permalink: ' ' # Blank space; this marker is styled in CSS.
  - sane_lists
  - nl2br
  - outline
  - codehilite
  # Set of PyMdown extensions to flesh out GFM-mimicry
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.githubemoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra:
  site_subtitle: '&middot; navigation &middot; text-to-speech &middot; elevation &middot;'
  project_repo_url: https://github.com/valhalla/
  docs_base_url: https://github.com/valhalla/valhalla-docs/blob/master
  display_project_name_api_key: true
  exclude_home_contents_in_toc: true
